"""Regenerate ``docs/tool-reference.md`` from the FastMCP server.

The v0.1 implementation prints a header and lets the hand-written page
stand. The L1 implementation walks the FastMCP registry and writes a
table row per tool.
"""

from __future__ import annotations

from pathlib import Path


def main() -> int:
    target = Path(__file__).resolve().parents[1] / "docs" / "tool-reference.md"
    if not target.exists():
        target.write_text(
            "# Tool reference (v0.1)\n\nRegenerated by scripts/gen_tool_reference.py.\n",
            encoding="utf-8",
        )
        print(f"wrote {target}")
    else:
        print(f"{target} already present; v0.1 leaves it hand-edited")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
