"""Regenerate the ADR nav block in ``mkdocs.yml`` from ADR file headers.

The ADR index (``docs/adr/README.md``) is already generated by
``gen_adr_index.py``; this keeps the MkDocs ``nav:`` ADR list in step from the
same source (each ADR's H1 title), so a new ADR cannot ship with a stale nav
(BL-097, audit 2026-06-14b DOC-1). A page absent from the nav is only an INFO
line under ``mkdocs build --strict``, so the drift never failed CI; the
companion test ``tests/unit/test_docs_nav.py`` runs this module's ``--check`` on
every PR instead.

Run with no arguments to rewrite the block in place; run with ``--check`` to exit
non-zero on drift without writing.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_ADR_HEADER = re.compile(r"^#\s+ADR\s+(\d+):\s+(.+?)\s*$", re.MULTILINE)

_BEGIN = "# BEGIN generated ADR nav (scripts/gen_mkdocs_adr_nav.py; make schema)"
_END = "# END generated ADR nav"
_INDENT = "      "


def adr_nav_entries(adr_dir: Path) -> list[str]:
    """One ``nav:`` line per ADR file, titled ``"<number> <H1 title>"``."""
    entries: list[str] = []
    for path in sorted(adr_dir.glob("[0-9][0-9][0-9][0-9]-*.md")):
        header = _ADR_HEADER.search(path.read_text(encoding="utf-8"))
        if header is None:
            continue
        number, title = header.group(1), header.group(2)
        entries.append(f'{_INDENT}- "{number} {title}": adr/{path.name}')
    return entries


def render(current: str, entries: list[str]) -> str:
    """Return ``current`` with the marked ADR nav block replaced by ``entries``."""
    lines = current.splitlines()
    begin = next((i for i, ln in enumerate(lines) if ln.strip() == _BEGIN), None)
    end = next((i for i, ln in enumerate(lines) if ln.strip() == _END), None)
    if begin is None or end is None or end < begin:
        raise SystemExit(
            f"mkdocs.yml is missing the ADR nav markers ({_BEGIN!r} / {_END!r})"
        )
    rebuilt = lines[: begin + 1] + entries + lines[end:]
    trailing = "\n" if current.endswith("\n") else ""
    return "\n".join(rebuilt) + trailing


def main(argv: list[str]) -> int:
    root = Path(__file__).resolve().parents[1]
    mkdocs = root / "mkdocs.yml"
    entries = adr_nav_entries(root / "docs" / "adr")
    current = mkdocs.read_text(encoding="utf-8")
    updated = render(current, entries)
    if "--check" in argv:
        if current != updated:
            print(
                "mkdocs.yml ADR nav is out of date; run `make schema` "
                "(or scripts/gen_mkdocs_adr_nav.py) to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"mkdocs.yml ADR nav is current ({len(entries)} entries)")
        return 0
    mkdocs.write_text(updated, encoding="utf-8")
    print(f"wrote {mkdocs} ADR nav ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
